gen_data_dir: "TowerEval-Data-v0.1/data/instructions_data/0_shot"
eval_data_dir: "TowerEval-Data-v0.1/data/raw_data"
gen_output_dir: "TowerEval-Data-v0.1/generations/0_shot"
eval_output_dir: "TowerEval-Data-v0.1/evaluations/0_shot"
tasks: 
  - name: mt
    subtasks:
      flores.en-de:
      flores.en-fr:
      flores.en-pt:
      flores.en-nl:
      flores.en-es:
      flores.en-it:
      flores.en-zh:
        gen_args:
        eval_args:
          metrics:
            chrf:
            bleu:
              tokenizer: zh
            comet:
              batch_size: 16
      flores.en-ko:
        gen_args:
        eval_args:
          metrics:
            chrf:
            bleu:
              tokenizer: ko-mecab
            comet:
              batch_size: 16
      flores.en-ru:
      flores.de-en:
      flores.fr-en:
      flores.pt-en:
      flores.nl-en:
      flores.es-en:
      flores.it-en:
      flores.zh-en:
      flores.ko-en:
      flores.ru-en:
      wmt23.en-de:
      wmt23.en-ru:
      wmt23.en-zh:
        eval_args:
          metrics:
            chrf:
            bleu:
              tokenizer: zh
            comet:
              batch_size: 16
      wmt23.de-en:
      wmt23.ru-en:
      wmt23.zh-en:
      tico19.en-es:
      tico19.en-fr:
      tico19.en-pt:
      tico19.en-ru:
      tico19.en-zh:
        gen_args:
        eval_args:
          metrics:
            chrf:
            bleu:
              tokenizer: zh
            comet:
              batch_size: 16
    metrics:
      chrf:
      bleu:
      comet:
        batch_size: 16
models:
  - name: gpt-3.5-turbo
    type: open-ai
    arguments:
      model: "gpt-3.5-turbo"
      max_tokens: 1024
      debug: True
      retry_max_attempts: 200
  - name: gpt-4
    type: open-ai
    arguments:
      model: "gpt-4"
      max_tokens: 1024
      debug: True
      retry_max_attempts: 200